### ISSUE TITLE
Help Request

### ISSUE THREAD

**Issue by Ksenia88** [RobinTail/chat#16]
I love the way you have developed this chat! I am interested in forking this to try and create a multi-room chat where users can connect without authentication to "read-only" but, will be forced to authenticate to post.

Do you have any thoughts or suggestions on how I may start to be able to integrate that into your current codebase or what may be required?

Thanks you for any assistance!

**Comment by RobinTail** [comment]
Hello. Glad to hear it :)
At first you should look at file `/source/api/chat.jsx` . In class constructor you can find, that client opens IO connection and mount event listeners depending on `appData.get('isAuthenticated')`. You should rewrite constructor and some other methods ( like `submitMessage()` and `iStartTyping()` ) to allow receiving messages without authentication, but decline sending messages.
`appData` - is an object defined in `/source/appData.jsx`. It parses JSON data, injected into view (`/views/index.ejs`) by server side ( `/handerls.js :: app()` ).
Also, in `/handlers.js` you can find the function `ioConnect()`, that called when new client connecting by IO. This function mounts event listeners and do some actions only when authenticated: broadcasts an information about new connected user, sends latest messages to a new connection. You should also rewrite this function.
You can find information about chat rooms at http://socket.io/docs/ .
Best wishes and have a nice coding. If you would like to make a pull request than, please do it in a new branch. Thank you :)

**Comment by Ksenia88** [comment]
Thank you very much for your detailed response! I believe I have that working correctly now based on all of your details for users without authentication! ))

I am also looking into an option of being able to embed this this into several pages for the multi-room aspect, however, because of the server-side authentication component of `handlers.js` do you think this is possible without a large refactor?

Ideally, I would like to take the compiled `index.js` and `<div id="AppContainer"></div>` wrapper and drop it into multiple different pages.

**Comment by RobinTail** [comment]
@Ksenia88 , I think yes. 
Look at the file `/routes.js` in the section `// default`. You can add routes for all of your pages there, maybe using wildcards or regular expressions ( `'/room/:number'` ).
If you want to keep authentication ability, taking just div-wrapper into several pages is insufficient, because server-side component `handlers.js` injects authentication information, user name, avatar and sound settings into page (view), see `/views/index.ejs :: script#applicationData`. So, client-side page is not static.
By the way, authentication is performed by _Passport_ and implemented in `/server.js` file. It serialize user's data into session, deserialize it and find user in MongoDB. `handlers.js` just use information, given by `deserializeUser()`.
I hope that I am helping you :)
P.S. More information about rooms: http://socket.io/docs/rooms-and-namespaces/

**Comment by Ksenia88** [comment]
Hi @RobinTail 

I guess what I am looking to ask is could you see this being embedded into pages on another server without using some kind of an iframe. Maybe I would have to move the authentication piece of `handlers.js` into some kind of RESTful api? 

I am not sure the best way to approach that. Do you have any thoughts? You are being a ton of help, thank you!

**Comment by RobinTail** [comment]
@Ksenia88
I think that RESTful API is a good idea.
Unfortunately, this chat was not designed as a module, it is a stand-alone application. Unfortunately, at this moment I have no free time till 25 of March to help you enough.
